name: hello-world
on: push
jobs:
  install-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cypress
        run: echo "npx install cypress typescript"
        
  run-tests:
          runs-on: ubuntu-latest
          steps:
            - name: Run Tests
              run: echo "npx test"